[project]
site_name = "Klab-BlockMatching"
site_url = "https://fepegar.github.io/Klab-BlockMatching/"
docs_dir = "docs/"
site_dir = "site/"
nav = [
  { "Home" = "index.md" },
  { "Installation" = "installation.md" },
  { "Tools" = "tools.md" },
  { "Building from source" = "building.md" },
]

[project.theme]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
scheme = "default"
toggle.icon = "lucide/monitor"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
